name: bazel-diff
run-name: Running bazel-diff on ${{ github.sha }}
on: [push]
jobs:
  echo-affected-targets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bazel
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run Command
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" run //tools:bazel-diff -- -V
